#!/usr/bin/env python3
"""
LlamaStyles Command Line Wrapper

This script serves as a wrapper to run the llamastyles command.
"""

import sys
from llamastyles.cli import main

if __name__ == "__main__":
    sys.exit(main()) 